name: Auto sync obsidian content

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
          submodules: true

      - run: |
          git submodule update --init --remote
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git commit -am "Auto sync obsidian content" || exit 0
          git push || exit 0
